use_shards: True
train_path: data/new_schema/train.ipc
valid_path: data/new_schema/valid.ipc
valid_subset_of_train:
source_type: ipc

residue_remapping: {
  "M(ox)": "M[UNIMOD:35]",
  "M(+15.99)": "M[UNIMOD:35]",
  "S(p)": "S[UNIMOD:21]", # Phosphorylation
  "T(p)": "T[UNIMOD:21]",
  "Y(p)": "Y[UNIMOD:21]",
  "S(+79.97)": "S[UNIMOD:21]",
  "T(+79.97)": "T[UNIMOD:21]",
  "Y(+79.97)": "Y[UNIMOD:21]",
  "Q(+0.98)": "Q[UNIMOD:7]", # Deamidation
  "N(+0.98)": "N[UNIMOD:7]",
  "Q(+.98)": "Q[UNIMOD:7]",
  "N(+.98)": "N[UNIMOD:7]",
  "C(+57.02)": "C[UNIMOD:4]", # Carboxyamidomethylation
  "(+42.01)": "[UNIMOD:1]", # Acetylation
  "(+43.01)": "[UNIMOD:5]", # Carbamylation
  "(-17.03)": "[UNIMOD:385]"}
